site_name: Edgebox Docs
site_url: https://docs.edgebox.io
docs_dir: src
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting-started.md
  - Contributing: contributing.md
  - Setup:
    - Installation: setup/installation.md
    - Configuration: setup/configuration.md
    - Execution: setup/execution.md
  - Others:
    - Code of Conduct: others/code-of-conduct.md
    - Common Errors: others/common-errors.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format