site_name: Edgebox Docs
site_url: https://docs.edgebox.io
docs_dir: src
nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
